<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Mics.Cli</RootNamespace>
    <AssemblyName>mics</AssemblyName>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>mics</ToolCommandName>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Mics.Cli</PackageId>
    <Version>1.0.0</Version>
    <Authors>Eduardo Zitinho</Authors>
    <Description>Music In C Sharp. Turn C# source code into music.</Description>
    <PackageTags>music;audio;sonification;code;csharp;cli;tool</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/eduardozitinho1/Mics</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Mics.Core/Mics.Core.csproj" />
    <ProjectReference Include="../Mics.CodeAnalysis/Mics.CodeAnalysis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
